services:
  postgres_academy:
    image: postgres:15.4
    container_name: postgres_academy
    env_file:
      - .env
    networks:
      - academy_network
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-academyuser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-academypass}
      POSTGRES_DB: ${POSTGRES_DB:-academydb}
    volumes:
      - academy_pgdata:/var/lib/postgresql/data
    restart: always

  django_academy:
    build: ./myAcademy
    container_name: django_academy
    env_file:
      - .env
    networks:
      - academy_network
    depends_on:
      - postgres_academy
    volumes:
      - academy_static:/usr/src/app/staticfiles
    expose:
      - "8000"
    restart: always

  nginx_academy:
    build: ./myNginx
    container_name: nginx_academy
    networks:
      - academy_network
    depends_on:
      - django_academy
    ports:
      - "8080:80"
    volumes:
      - academy_static:/usr/src/app/staticfiles
    restart: always

networks:
  academy_network:

volumes:
  academy_pgdata:
  academy_static:
